### ISSUE TITLE
Non-standard devkitPro installation path not detected on Windows

### ISSUE THREAD

**Issue by arcaneArtisan** [Nightkingale/WUHB-Packager#1]
Hi, I'm running into an issue with this tool running in Windows 10.

When attempting to launch the program, I get the error saying that I must install wubtool "correctly" to be able to use the program, even though it's fully installed. Looking into the source code, I believe this is because it's searching for a hard coded path of c:\devkitPro\* for devkitPro's installation, while I installed it to D:\applications\devkitPro\*

Adding a .ini file to set a custom devkitPro\tools\bin directory, a dialog available at boot to set it to a custom path, or at least having the program check within the same directory that the executable is placed in, would probably be all that needs to be changed to fix this.

In my case I'm just going to move the directory, but I thought I'd add the Issue here so you can fix it for future users. Thank you!

**Comment by Nightkingale** [comment]
Hey, thanks for submitting this issue! I appreciate it!

You are correct, the paths are currently hard-coded to wherever devkitPro should install by default on both Windows and Linux. I am not a fan of this behavior myself, so I have been looking into this issue over the past while, even before you submitted this. The problem is that I can't find a solution I like that would replace this behavior.

My current idea I have been toying around with was to look at the environment variables which devkitPro would set during install. As far as I can tell, this approach shouldn't be much of a hassle to get going in a Linux environment. However, I can't really say the same for Windows, which is a shame because I wrote WUHB Packager particularly for Windows users.

Currently, my `DEVKITPRO` variable is set to `/opt/devkitpro`. Unless my installation is borked, I don't fully understand how I can use this variable on Windows. I assume it's because devkitPro stuff is traditionally supposed to be ran under MSYS2, rather than just through Command Prompt or Terminal.

I feel like I might be hitting it on the money with my idea, but I just don't know how to implement it. I will continue to toy with this idea, and consider other solutions if nothing else.
